apiVersion: v1
kind: Service
metadata:
  name: flask-backend-service  # Nombre único para el servicio
spec:
  type: ClusterIP  # Usa LoadBalancer si necesitas exponerlo externamente
  selector:
    app: flask-backend
  ports:
    - port: 5001
      targetPort: 5001
