apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend-deployment  # Nombre único para el despliegue
spec:
  replicas: 3  # Ajusta el número de réplicas según sea necesario
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      containers:
      - name: flask-backend
        image: wilmans/flask-backend:1.0.0  # Reemplaza con tu usuario de Docker Hub y nombre de imagen
        ports:
        - containerPort: 5001
