# Usa una imagen ligera de Python
FROM python:3.9-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el código del balanceador de carga
COPY load_balancer.py /app

# Instalar Flask y requests
RUN pip install Flask requests

# Exponer el puerto de la aplicación
EXPOSE 8080

# Ejecutar la aplicación Flask
CMD ["python", "load_balancer.py"]

