# Use una imagen ligera de Python
FROM python:3.9-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el código de la app
COPY backend.py /app

# Instalar Flask
RUN pip install Flask

# Exponer el puerto de la aplicación
EXPOSE 5001

# Ejecutar la aplicación Flask
CMD ["python", "backend.py"]

